name = "Lunarie"
author = "sammyette"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2dedc25fe324f9da759e77f425bb229e17f9e0019a76fa8d48970537a1e6afc"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
