name = "Lunarie"
author = "sammyette"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85ee55961fbfa674842a675f8fffa4b2af3078bcc49a5c2154f724bf0e0cd125"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2"]
