name = "Lunarie"
author = "sammyette"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9335b00ec2d07b03dff455bdd2f6b8f18b9a4dba719083f111340dfe5626eaf"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
