name = "Lunarie"
author = "sammyette"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df15e4e6eacd0dd84a97a42c1c19b178d3e04af88349f0c80d4d1c1c479f7b11"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
