name = "Lunarie"
author = "sammyette"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58363893b37742f1111cbd21e9ee93d8b6cf9d3ab7b2a46f3fc228e655290d2c"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2"]
